#! /usr/bin/env python
# -*- coding: utf-8 -*-

#    File Name：       练习1
#    Description :
#    Author :          SanYapeng
#    date：            2019-03-05
#    Change Activity:  2019-03-05:

cars = 100
space_in_a_car = 4.0
drivers = 30
passengers = 90
cars_not_driver = cars - drivers
cars_driven = drivers
carpool_capacity = cars_driven + space_in_a_car
average_passengers_per_car = passengers / cars_driven


